query GetTransactions {
    transactions {
        id
        user {
            firstName
            lastName
        }
        description
        merchant {
            name
        }
        debit
        credit
        amount
    }
}
