#import "./fragments/userFragment.gql"
#import "./fragments/merchantFragment.gql"

query GetTransactions {
    transactions {
        id
        user {
            ...userData
        }
        description
        merchant {
            ...merchantData
        }
        debit
        credit
        amount
    }
}